# Generated by Django 3.2.4 on 2021-10-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_auto_20210407_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='porfolio/carousel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.project')),
            ],
        ),
    ]
